const express = require('express')
const app = express()
const bodyParser = require('body-parser');
const errorHandler = require('./middleware/errorHandler')
const userController = require('./controller/users.controller')
const productController = require("./controller/product.controller")
const { auth, register, validUser } = require('./domain/users.domain')
const productDomain = require('./domain/product.domain')
const verifytoken = require('./authorization/verifytoken')
const adminController = require('./controller/admin.controller')
const adminRouter = require('./controller/admin.router')
const razorpayRouter = require('./controller/razorpay.controller')
const router = express.Router()
const cors = require('cors')

app.use(bodyParser.urlencoded({ extended: false }))
// app.use(express.urlencoded({ extended: false }));
app.use(bodyParser.json())
// app.use(cors)
app.use('/razorpay', razorpayRouter)
app.post('/authenticate', auth)
app.post('/register', register)
app.use('/admin', adminRouter)
app.post('/reg', productDomain.reg)
app.post('/login', productDomain.logg)
app.use('/products', productController)
app.get('/validuser', validUser)
app.use(verifytoken)
app.use('/users', userController)
// app.use('/admin', adminController)
app.use(errorHandler)

app.listen(5000, console.log('server is running on port 5000'))