const express = require('express')
const app = express()
const bodyParser = require('body-parser');
const errorHandler = require('./middleware/errorHandler')
const userController = require('./controller/users.controller')
const productController = require("./controller/product.controller")
const { auth, register } = require('./domain/users.domain')
const verifytoken = require('./authorization/verifytoken')
const router = express.Router()

app.use(bodyParser.urlencoded({ extended: false }))
app.use(bodyParser.json())
app.post('/authenticate', auth)
app.post('/register', register)
app.use(verifytoken)
app.use('/users', userController)
app.use('/products', productController)
app.use(errorHandler)

app.listen(3000, console.log('server is running on port 3000'))